# Generated by Django 5.0.14 on 2026-01-13 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(help_text='Raw ingredients text that was analyzed')),
                ('detected_ingredients', models.IntegerField(help_text='Number of ingredients detected')),
                ('overall_rating', models.CharField(choices=[('BEST', 'Best'), ('GOOD', 'Good'), ('AVERAGE', 'Average'), ('BAD', 'Bad'), ('AVOID', 'Avoid')], max_length=20)),
                ('overall_score', models.DecimalField(decimal_places=1, help_text='Score from 0.0 to 10.0', max_digits=3)),
                ('good_ingredients', models.JSONField(default=list, help_text='List of beneficial ingredients')),
                ('bad_ingredients', models.JSONField(default=list, help_text='List of harmful ingredients')),
                ('neutral_ingredients', models.JSONField(default=list, help_text='List of neutral ingredients')),
                ('recommendation_text', models.TextField(help_text='AI-generated health recommendation')),
                ('allergen_warnings', models.JSONField(blank=True, default=list, help_text='List of detected allergens')),
                ('health_concerns', models.JSONField(blank=True, default=list, help_text='List of health concerns')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(help_text='Time taken to analyze in seconds')),
                ('from_cache', models.BooleanField(default=False, help_text='Whether result came from cache')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Analysis',
                'verbose_name_plural': 'Product Analyses',
                'ordering': ['-analysis_date'],
                'indexes': [models.Index(fields=['-analysis_date'], name='analysis_pr_analysi_7ad6fd_idx'), models.Index(fields=['user', '-analysis_date'], name='analysis_pr_user_id_74a315_idx'), models.Index(fields=['overall_rating'], name='analysis_pr_overall_4114fc_idx')],
            },
        ),
    ]
