# Generated by Django 5.0.14 on 2026-01-13 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.JSONField(blank=True, default=list, help_text='List of allergies')),
                ('dietary_restrictions', models.JSONField(blank=True, default=list, help_text='Dietary restrictions (vegan, halal, etc.)')),
                ('health_conditions', models.JSONField(blank=True, default=list, help_text='Health conditions (diabetes, hypertension, etc.)')),
                ('avoid_ingredients', models.JSONField(blank=True, default=list, help_text='Ingredients to avoid')),
                ('preferred_categories', models.JSONField(blank=True, default=list, help_text='Preferred product categories')),
                ('notification_enabled', models.BooleanField(default=True)),
                ('scan_reminder', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
