// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTd_HD_VrI9UD_2vbkwEMmXH2TmMEPX1M',
    appId: '1:819106507078:web:bfc98eee9a77e8c7e21d47',
    messagingSenderId: '819106507078',
    projectId: 'safepick-9c178',
    authDomain: 'safepick-9c178.firebaseapp.com',
    storageBucket: 'safepick-9c178.firebasestorage.app',
    measurementId: 'G-6LE8K3FT84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbm3DhTJPQlLOws1GHmBy1pLuekUv5yEA',
    appId: '1:819106507078:android:77f786fdee678ce9e21d47',
    messagingSenderId: '819106507078',
    projectId: 'safepick-9c178',
    storageBucket: 'safepick-9c178.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbemQj36M3kb8v8hGMcprOBAM2kwYVObY',
    appId: '1:819106507078:ios:8f25422ee043a509e21d47',
    messagingSenderId: '819106507078',
    projectId: 'safepick-9c178',
    storageBucket: 'safepick-9c178.firebasestorage.app',
    iosClientId: '819106507078-pco5aioo2vlrlg6jcfoohd201ui48k3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.safepickMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbemQj36M3kb8v8hGMcprOBAM2kwYVObY',
    appId: '1:819106507078:ios:8f25422ee043a509e21d47',
    messagingSenderId: '819106507078',
    projectId: 'safepick-9c178',
    storageBucket: 'safepick-9c178.firebasestorage.app',
    iosClientId: '819106507078-pco5aioo2vlrlg6jcfoohd201ui48k3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.safepickMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTd_HD_VrI9UD_2vbkwEMmXH2TmMEPX1M',
    appId: '1:819106507078:web:41553067ac7c2589e21d47',
    messagingSenderId: '819106507078',
    projectId: 'safepick-9c178',
    authDomain: 'safepick-9c178.firebaseapp.com',
    storageBucket: 'safepick-9c178.firebasestorage.app',
    measurementId: 'G-3BCNQR9HYG',
  );
}
